name: "article_uploader"
description: "Upload .md files through API"
inputs:
  article_folder:
    description: "Folder for article that needs to be uploaded"
    required: true
  version:
    description: "Version of the action to be run"
    required: false
    default: "v0_1_3" #Change value in .build_version
outputs:
  status:
    description: "Status of article upload API request"
  errors:
    description: "Any errors encountered"
  detail:
    description: "Any detail that needs to be given regarding the completed status"
runs:
  using: "node20"
  main: "index.js"
